name: Json parse test

on:
  workflow_dispatch:
    inputs:
      parameters_json:
        type: string
        required: true

jobs:
  build_and_deploy:
    name: Json parse test
    runs-on: ubuntu-latest
    steps:
      - name: Parse json input
        id: json
        run: |
          echo ${{ fromJson(github.event.inputs.parameters_json).targetPlatform }}
